CREATE TABLE NACE_DATA
(
ORDER_ID NUMERIC(22) NOT NULL,
LEVEL VARCHAR(22)  NOT NULL,
CODE VARCHAR(22)  NOT NULL,
PARENT VARCHAR(22),
DESCRIPTION VARCHAR(1000),
ITEMS_INCLUDE VARCHAR(6000),
ITEMS_ALSO_INCLUDE VARCHAR(2000),
RULING VARCHAR(1000),
ITEMS_EXCLUDE VARCHAR(2000),
REFERENCE_TO_ISIC VARCHAR(1000)
);
CREATE INDEX IDX_ORDER_ID ON NACE_DATA(ORDER_ID);